# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a28acb32cb8b78bc8b670a2fe8004a4ca493fb98faaf5dcf36964c834f9bc67ce0b13225cd059186c989a0ea5751f77f173fa3faf7aafee7ddf7313867bb651a

test:
  secret_key_base: 83c044c111c041d4d39a9ed55ae62ffbba267eaf8d4331fa72a41c4040fe75320edcdfba333877b81b6952e24b7e469ee8b7c71ed264dab533ce2ecfda8f8028

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
